server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: employee-api
          uri: lb://EMPLOYEE-API
          predicates:
            - Path=/employee/**
        - id: payroll-api
          uri: lb://PAYROLL-API
          predicates:
            - Path=/payroll/**
        - id: report-api
          uri: lb://REPORT-API
          predicates:
            - Path=/report-api/**
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}