spring:
  application:
    name: registry
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability:  1.0
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
